name: Monthly Average Air Quality Update

on:
  schedule:
    # Runs on the 1st day of every month at 3:00 AM UTC
    - cron: '0 3 1 * *'
  workflow_dispatch:

env:
  SHEET_ID: ${{ secrets.SHEET_ID }}
  R_LIBS_USER: ~/.local/R/library

jobs:
  update-monthly-air-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Cache R package library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "config", "googlesheets4", "lubridate", 
            "jsonlite", "httr", "dplyr", "readr", "tidyr"
          ), quiet = TRUE)'

      - name: Run monthly update
        run: Rscript run_update_monthly.R

      - name: Confirm success
        run: echo "✅ Monthly Air Quality update completed successfully!"
